/// Flutter icons ClothesIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ClothesIcons
///      fonts:
///       - asset: fonts/ClothesIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ClothesIcons {
  ClothesIcons._();

  static const _kFontFam = 'ClothesIcons';
  static const String? _kFontPkg = null;

  static const IconData saia = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData short01 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calcas = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calcas_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData conjunto_short_blusa = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camiseta = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vestido_colado = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vestido = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blusa_alca = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
